<?xml version="1.0" encoding="utf-8"?><Database Name="SolutionCore" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=Hans-PC\SQLExpress;Initial Catalog=SolutionCore;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SolutionCoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.companies" Member="companies">
    <Type Name="company">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="cvr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ceo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="startup_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="is_activ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="financial_report" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="advertising_protected" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="empoye_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="zip_code_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="company_contact" Member="contacts" ThisKey="id" OtherKey="company_id" Type="contact" />
      <Association Name="zip_code_company" Member="zip_code" ThisKey="zip_code_id" OtherKey="id" Type="zip_code" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zip_codes" Member="zip_codes">
    <Type Name="zip_code">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="zip_code" Member="zip_code1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="zip_code_company" Member="companies" ThisKey="id" OtherKey="zip_code_id" Type="company" />
    </Type>
  </Table>
  <Table Name="dbo.contacts" Member="contacts">
    <Type Name="contact">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="company_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="company_contact" Member="company" ThisKey="company_id" OtherKey="id" Type="company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="access_level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="role_user" Member="users" ThisKey="id" OtherKey="role_id" Type="user" />
    </Type>
  </Table>
  <Table Name="dbo.settings" Member="settings">
    <Type Name="setting">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="site_name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="logo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="role_user" Member="role" ThisKey="role_id" OtherKey="id" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
</Database>